name: pataforce8-klipper # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Installs the Klipper host software. # 79 char long summary
description: |
  Installs Klipper host software for use on Ubuntu Core devices. The 
  Klipper repository is available here: https://github.com/Klipper3d/klipper
  All code falls under the GPL-3.0 License.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

# apps:
#   # hello:
#   #   command: bin/hello
#   klipper:
#     command: 
#     daemon: simple

parts:
  klipper:
     source: klipper
     plugin: python
     python-requirements:
     - /root/parts/klipper/src/scripts/klippy-requirements.txt
    #  stage-packages: #These taken from Ubuntu 22 install script
    #   - virtualenv
    #   - python3-dev #possible error in Klipper repo, this was python-dev
    #   - libffi-dev
    #   - build-essential
    #   - libncurses-dev
    #   - libusb-dev
    #   - avrdude
    #   - gcc-avr
    #   - binutils-avr
    #   - avr-libc
    #   - stm32flash
    #   - dfu-util
    #   - libnewlib-arm-none-eabi
    #   - gcc-arm-none-eabi
    #   - binutils-arm-none-eabi
    #   - libusb-1.0-0 #possible error in Klipper repo, this was libusb-1.0.0